export const HEADER = `/**
 * This file was automatically generated by the ATFW tool.
 * Do not modify this file directly. Instead, modify the source code and regenerate the tests.
 * https://github.com/kfarkasHU/atfw
 */
`;