name: PR Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run gha:build

      - name: Lint
        run: npm run gha:lint

      - name: Run Generated Test Harness
        run: bash ./test-against-all.sh
